### ISSUE TITLE
Suggest to drop support for Python 3.2

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/socos#62]
As evident from #55, we are now running into the problem with Travis checks for Python 3.2, that we have also had for SoCo. The problem is that pylint support for 3.2 has been cut.

In principle we can continue to support Python 3.2 and simply disable pylint for it, but considering that socos is an application I think we can allow ourselves to simply cut the support.

Any thought or opinions?

**Comment by petteraas** [comment]
+1 for removing the support for 3.2!

**Comment by stefankoegl** [comment]
+1

**Comment by KennethNielsen** [comment]
Fixed by #65
