### ISSUE TITLE
upload version 0.2 onto pip

### ISSUE THREAD

**Issue by philippkeller** [SoCo/socos#68]
When installing via pip I get the old 0.1 version, however, this is from 2014, quite a while back. Also, version 0.1 is using soco 0.7, whereas soco is now at version 0.13.

Can you upload the new version to pypi? I was trying that but obviously I'm not allowed as I'm not the package author.

**Comment by stefankoegl** [comment]
Unfortunately we haven't done a proper release of socos in quite some time. #57 is the latest (open) release ticket, but I understand that 0.2 has been tagged but was never properly released.

I'll review which steps of the release have been done, and which are still open, and maybe initiate a full release soon.

**Comment by stefankoegl** [comment]
I have just uploaded version 0.2 to PyPI.
